
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 07 14:26:00 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INPUT = 11;
  public static final int ELSE = 15;
  public static final int PLUS = 17;
  public static final int INT = 4;
  public static final int SEMI = 23;
  public static final int CHAR = 5;
  public static final int WHILE = 16;
  public static final int LEFTPAR = 19;
  public static final int END = 10;
  public static final int RIGHTPAR = 20;
  public static final int IF = 13;
  public static final int ID = 28;
  public static final int TILDE = 26;
  public static final int BEGIN = 9;
  public static final int DO = 14;
  public static final int COMMA = 24;
  public static final int EOF = 0;
  public static final int LEFTBRA = 7;
  public static final int MAIN = 2;
  public static final int DOTDOT = 21;
  public static final int CONST = 29;
  public static final int DOT = 27;
  public static final int ARROW = 25;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int RIGHTBRA = 8;
  public static final int BOOL = 6;
  public static final int OUTPUT = 12;
  public static final int MUL = 18;
  public static final int VAR = 3;
}

